// Catálogo de ejercicios. La clave es el nombre del archivo PNG dentro de
// public/Ejercicios/<carpeta>/ y el valor es el nombre que se muestra en pantalla.

export const GRUPOS = [
  {
    carpeta: '1_Pectorales',
    nombre: 'Pectorales',
    ejercicios: {
      'barbell-bench-press': 'Press de banca con barra',
      'barbell-declined-bench-press': 'Press de banca declinado con barra',
      'chest-press-machine': 'Press de banca en máquina',
      'close-grip-bench-press': 'Press de banca agarre cerrado',
      'dumbbell-bench-press': 'Press de banca con mancuernas',
      'dumbbell-declined-bench-press': 'Press declinado con mancuernas',
      'dumbbell-fly': 'Aperturas con mancuernas',
      'high-cable-rear-delt-fly': 'Cruces inversos en polea alta',
      'incline-barbell-bench-press': 'Press inclinado con barra',
      'incline-dumbbell-bench-press': 'Press inclinado con mancuernas',
      'incline-dumbbell-fly': 'Aperturas inclinadas con mancuernas',
      'peck-deck': 'Aperturas en máquina (Peck Deck)',
      'push-ups': 'Flexiones',
    },
  },
  {
    carpeta: '2_Espalda',
    nombre: 'Espalda',
    ejercicios: {
      'barbell-bent-over-rows-supinated-grip': 'Remo con barra agarre supinado',
      'barbell-deadlift': 'Peso muerto con barra',
      'barbell-pullover': 'Pullover con barra',
      'barbell-row': 'Remo con barra',
      'barbell-shrug': 'Encogimiento de hombros con barra',
      'barbell-stiff-leg-deadlift': 'Peso muerto rumano con barra',
      'barbell-sumo-deadlift': 'Peso muerto sumo con barra',
      'barbell-upright-row': 'Remo alto con barra',
      'behind-neck-pulldown': 'Jalón tras nuca',
      'behind-the-neck-pull-up': 'Dominadas tras nuca',
      'bent-over-lateral-raise': 'Elevaciones posteriores (pájaro)',
      'cable-one-arm-lateral-raise': 'Elevación lateral en polea a una mano',
      'close-grip-pulldown': 'Jalón al pecho agarre cerrado',
      'dumbbell-bent-over-row-single-arm': 'Remo con mancuerna a una mano',
      'dumbbell-bent-over-rows': 'Remo inclinado con mancuernas',
      'dumbbell-deadlift': 'Peso muerto con mancuernas',
      'dumbbell-lateral-raise': 'Elevación lateral con mancuernas',
      'dumbbell-pullover': 'Pullover con mancuerna',
      'dumbbell-shrugs': 'Encogimiento de hombros con mancuernas',
      'dumbbell-stiff-leg-deadlift': 'Peso muerto rumano con mancuernas',
      'kettlebell-sumo-deadlift': 'Peso muerto sumo con kettlebell',
      'kickback': 'Patada de tríceps',
      'lateral-mini-band-walk': 'Caminata lateral con minibanda',
      'medicine-ball-deadlift': 'Peso muerto con balón medicinal',
      'pull-up-with-a-supinated-grip': 'Dominadas agarre supinado',
      'pull-up': 'Dominadas',
      'reverse-grip-pulldown': 'Jalón al pecho agarre invertido',
      'rope-ab-pulldown': 'Abdominales en polea con cuerda',
      'rope-pulldown': 'Jalón en polea con cuerda',
      'seated-cable-row': 'Remo sentado en polea',
      'single-leg-bodyweight-deadlift': 'Peso muerto a una pierna',
      'standing-cable-kickback': 'Patada de glúteo en polea',
      'straight-arm-lat-pulldown': 'Jalón dorsal con brazos rectos',
      't-bar-rows': 'Remo en barra T',
      'trap-bar-deadlift': 'Peso muerto con barra hexagonal',
      'wide-grip-pulldown': 'Jalón con agarre ancho',
    },
  },
  {
    carpeta: '3_Hombros',
    nombre: 'Hombros',
    ejercicios: {
      'alternate-dumbbell-front-raise-neutral-grip': 'Elevación frontal alterna agarre neutro',
      'barbell-front-raise': 'Elevación frontal con barra',
      'dumbbell-front-raise': 'Elevación frontal con mancuernas',
      'dumbbell-shoulder-press': 'Press de hombro con mancuernas',
      'one-arm-low-pulley-front-raise-neutral-grip': 'Elevación frontal en polea baja',
      'seated-barbell-shoulder-press': 'Press militar sentado con barra',
      'seated-behind-the-neck-barbell-shoulder-press': 'Press tras nuca sentado',
      'single-arm-cable-front-raise': 'Elevación frontal en polea a una mano',
      'smith-machine-shoulder-press': 'Press de hombros en máquina Smith',
      'standing-barbell-shoulder-press': 'Press militar de pie',
      'standing-behind-the-neck-barbell-shoulder-press': 'Press militar de pie tras nuca',
      'two-handed-dumbbell-front-raise': 'Elevación frontal a dos manos',
    },
  },
  {
    carpeta: '4_Biceps',
    nombre: 'Bíceps',
    ejercicios: {
      'alternating-dumbbell-curl': 'Curl alterno con mancuernas',
      'barbell-curl': 'Curl con barra',
      'dumbbell-concentration-curl': 'Curl concentrado',
      'ez-barbell-curl': 'Curl con barra EZ',
      'ez-barbell-preacher-curl': 'Curl predicador con barra EZ',
      'hammer-curl': 'Curl martillo',
      'incline-dumbbell-curl': 'Curl inclinado con mancuernas',
      'lying-leg-curl': 'Curl femoral tumbado',
      'reverse-barbell-curl': 'Curl invertido con barra',
      'rope-cable-curl': 'Curl con cuerda en polea',
      'seated-barbell-wrist-curl': 'Curl de muñeca sentado',
      'seated-barbell-wrist-extension': 'Extensión de muñeca sentado',
      'seated-leg-curl': 'Curl femoral sentado',
      'single-arm-low-pulley-cable-curl': 'Curl en polea baja a una mano',
      'standing-high-pulley-cable-curl': 'Curl en polea alta de pie',
      'straight-bar-low-pulley-cable-curl': 'Curl con barra en polea baja',
    },
  },
  {
    carpeta: '5_Triceps',
    nombre: 'Tríceps',
    ejercicios: {
      'bench-dips': 'Fondos en banco',
      'dumbbell-overhead-triceps-extension': 'Extensión sobre la cabeza con mancuerna',
      'lying-dumbbell-triceps-extension': 'Extensión tumbado con mancuernas',
      'lying-triceps-extension': 'Extensión de tríceps tumbado',
      'parallel-dip-bar': 'Fondos en paralelas',
      'reverse-grip-cable-triceps-extension-with-barbell': 'Extensión en polea agarre inverso',
      'seated-barbell-french-press': 'Press francés sentado',
      'single-arm-cable-triceps-extension-with-supinated-grip': 'Extensión en polea a una mano supinado',
      'single-arm-cable-triceps-extension': 'Extensión en polea a una mano',
      'triceps-pressdown': 'Extensión de tríceps en polea',
    },
  },
  {
    carpeta: '6_Abdominales',
    nombre: 'Abdominales',
    ejercicios: {
      'band-seated-hip-abduction': 'Abducción de cadera sentado con banda',
      'bent-knee-reverse-crunch': 'Encogimiento inverso de rodillas',
      'cable-crossover': 'Cruce de poleas',
      'cable-rope-puschdown': 'Extensión en polea con cuerda',
      'crunch-machine': 'Abdominales en máquina',
      'crunch': 'Crunch',
      'hanging-leg-raise': 'Elevación de piernas colgado',
      'long-arm-crunch': 'Crunch con brazos estirados',
      'oblique-crunch': 'Crunch oblicuo',
      'plank': 'Plancha',
      'seated-hip-abduction-machine': 'Abducción de cadera en máquina',
      'side-lying-leg-raise': 'Elevación de pierna de costado',
      'standing-cable-abduction': 'Abducción en polea de pie',
      'standing-knee-raise': 'Elevación de rodillas de pie',
    },
  },
  {
    carpeta: '7_Piernas',
    nombre: 'Piernas',
    ejercicios: {
      '1-5-rep-bodyweight-squats': 'Sentadillas 1.5 repeticiones',
      'banded-glute-bridge': 'Puente de glúteos con banda',
      'barbell-bulgarian-split-squat': 'Sentadilla búlgara con barra',
      'barbell-hip-thrust': 'Elevación de cadera con barra',
      'bodyweight-bulgarian-split-squat': 'Sentadilla búlgara sin peso',
      'bodyweight-frog-pump': 'Elevación en posición de rana',
      'bodyweight-glute-bridge': 'Puente de glúteos',
      'bodyweight-squat': 'Sentadilla sin peso',
      'burpees': 'Burpees',
      'donkey-kicks': 'Patadas de burro',
      'dumbbell-goblet-squat': 'Sentadilla goblet con mancuerna',
      'dumbbell-step-up': 'Step up con mancuernas',
      'fire-hydrants': 'Hidrantes',
      'front-squat': 'Sentadilla frontal',
      'glute-ham-raise': 'Elevación de femoral (GHD)',
      'good-morning': 'Buenos días con barra',
      'groiners': 'Groiners',
      'hack-squat': 'Sentadilla hack',
      'jump-squat': 'Sentadilla con salto',
      'leg-extension': 'Extensión de piernas',
      'leg-press': 'Prensa de piernas',
      'lunge': 'Zancada',
      'medicine-ball-squat': 'Sentadilla con balón medicinal',
      'mini-band-air-squat': 'Sentadilla con minibanda',
      'side-lying-hip-raise': 'Elevación de cadera de costado',
      'single-leg-extension': 'Extensión a una pierna',
      'single-leg-glute-bridge': 'Puente de glúteos a una pierna',
      'smith-machine-frog-pump': 'Elevación de rana en Smith',
      'smith-machine-hip-thrust': 'Elevación de cadera en Smith',
      'squat-sit-to-reach': 'Sentadilla postural',
      'squat': 'Sentadilla',
    },
  },
  {
    carpeta: '8_Gemelos',
    nombre: 'Gemelos',
    ejercicios: {
      'seated-calf-raise': 'Elevación de gemelos sentado',
      'standing-calf-raise': 'Elevación de gemelos de pie',
    },
  },
  {
    carpeta: '9_Otros',
    nombre: 'Otros',
    ejercicios: {
      'banded-clams': 'Almejas con banda',
      'barbell-push-press': 'Push press con barra',
      'bird-dog': 'Superman en cuadrupedia',
      'duck-walk': 'Caminata de pato',
      'dumbbell-push-press': 'Push press con mancuernas',
      'kettlebell-swings': 'Swings con kettlebell',
      'knee-tuck-jumps': 'Salto rodillas al pecho',
      'wall-sit': 'Sentadilla isométrica en pared',
    },
  },
];

// Devuelve la ruta pública de la imagen de un ejercicio.
export const rutaImagen = (carpeta, slug) =>
  `/Ejercicios/${carpeta}/${slug}.png`;

// Busca el nombre en español a partir del slug, sin importar el grupo.
export const nombreDeSlug = (slug) => {
  for (const g of GRUPOS) {
    if (g.ejercicios[slug]) return g.ejercicios[slug];
  }
  return slug;
};
