# Generated by Django 6.0.7 on 2026-08-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='El pensamiento o idea a registrar')),
                ('category', models.CharField(blank=True, choices=[('profesional', 'Profesional'), ('liderazgo', 'Liderazgo'), ('personal', 'Personal'), ('tecnico', 'Técnico'), ('relaciones', 'Relaciones'), ('mentalidad', 'Mentalidad'), ('otro', 'Otro')], default='otro', max_length=20, null=True)),
                ('sentiment', models.CharField(blank=True, choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('neutro', 'Neutro')], default='neutro', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Thoughts',
                'ordering': ['-created_at'],
            },
        ),
    ]
