# Generated by Django 6.0.7 on 2026-08-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='category',
            field=models.CharField(blank=True, choices=[('sin_categoria', 'Sin Categoría'), ('profesional', 'Profesional'), ('liderazgo', 'Liderazgo'), ('personal', 'Personal'), ('técnico', 'Técnico'), ('relaciones', 'Relaciones'), ('mentalidad', 'Mentalidad'), ('salud', 'Salud'), ('finanzas', 'Finanzas'), ('crecimiento', 'Crecimiento'), ('otro', 'Otro')], default='sin_categoria', max_length=20, null=True),
        ),
    ]
