# Generated by Django 6.0.7 on 2026-08-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0002_alter_thought_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='category',
            field=models.CharField(blank=True, choices=[('sin_categoria', 'Sin Categoría'), ('profesional', 'Profesional'), ('liderazgo', 'Liderazgo'), ('personal', 'Personal'), ('técnico', 'Técnico'), ('relaciones', 'Relaciones'), ('mentalidad', 'Mentalidad'), ('salud', 'Salud'), ('finanzas', 'Finanzas'), ('crecimiento', 'Crecimiento'), ('comunicación', 'Comunicación'), ('estrategia', 'Estrategia'), ('decisiones', 'Decisiones'), ('conflictos', 'Conflictos'), ('motivación', 'Motivación'), ('autoconfianza', 'Autoconfianza'), ('familia', 'Familia'), ('tiempo', 'Tiempo/Productividad'), ('creatividad', 'Creatividad'), ('desafíos', 'Desafíos'), ('éxitos', 'Éxitos/Logros'), ('emociones', 'Emociones'), ('aprendizaje', 'Aprendizaje'), ('objetivos', 'Objetivos'), ('miedos', 'Miedos/Inseguridades'), ('oportunidades', 'Oportunidades'), ('feedback', 'Crítica/Retroalimentación'), ('experiencias', 'Experiencias'), ('ideas', 'Ideas'), ('otro', 'Otro')], default='sin_categoria', max_length=20, null=True),
        ),
    ]
