# Generated by Django 6.0.7 on 2026-08-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('gym', models.BooleanField(default=False)),
                ('creatina', models.BooleanField(default=False)),
                ('vitamina_d', models.BooleanField(default=False)),
                ('omega3', models.BooleanField(default=False)),
                ('magnesio', models.BooleanField(default=False)),
                ('zinc', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
