# Generated by Django 6.0.7 on 2026-08-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('proteina', 'Proteína'), ('carbohidrato', 'Carbohidrato'), ('verdura', 'Verdura'), ('fruta', 'Fruta'), ('lacteo', 'Lácteo'), ('bebida', 'Bebida'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComidaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('momento', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena'), ('snack', 'Snack')], max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('alimentos', models.ManyToManyField(blank=True, to='tracker.alimento')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
