# Generated by Django 6.0.7 on 2026-08-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alimento_comidadiaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='porcion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
