# Generated by Django 6.0.7 on 2026-08-15 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alimento_descripcion_alimento_porcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo', models.CharField(choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('piernas', 'Piernas'), ('hombros', 'Hombros'), ('brazos', 'Brazos'), ('core', 'Core'), ('cardio', 'Cardio'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('gif_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['grupo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EjercicioRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('series', models.IntegerField(blank=True, null=True)),
                ('repeticiones', models.IntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nota', models.TextField(blank=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ejercicio')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
