# Generated by Django 6.0.7 on 2026-08-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_ejercicio_ejerciciorealizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('momento', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena'), ('snack', 'Snack')], max_length=20)),
                ('detalle', models.TextField()),
            ],
            options={
                'ordering': ['-fecha', 'momento'],
            },
        ),
    ]
